### ISSUE TITLE
macbook touches

### ISSUE THREAD

**Issue by akaRem** [gregoryfabry/checkerboard#2]
Hi!
In readme there is an animation where you move cards by touching macbook display. How is it possible?

**Comment by gregoryfabry** [comment]
Hi there Ivan

Once you have checkerboard installed you'll want to run (this is all in checkerboard folder in your terminal):

    node examples/server.js

Then you need a way to serve the static content, I recommend http-server which is quick:

    npm install http-server -g
    http-server

Navigate to local host:8080/examples/cards.html in your browser, open in multiple windows/on multiple computers for the full effect.

**Comment by gregoryfabry** [comment]
Let me know if that worked, I would love feedback! -G

**Comment by akaRem** [comment]
It requires sudo:

```
$ sudo node examples/server.js
```

Server works, webapp works.

**Comment by akaRem** [comment]
How do you move cards by touching macbook screen?
Do you use other hand?

**Comment by gregoryfabry** [comment]
Yup. It uses JavaScript library interactjs. It's multitouch so use two
fingers to rotate if your device has a touch screen.

**Comment by akaRem** [comment]
Nice trick. :)
